spring:
  application:
    name: regist-center
  config:
    import: optional:configserver:http://localhost:7755/
  cloud:
    config:
      name: allinone-eureka2
      label: master
      profile: test
      uri: http://localhost:7755/
