spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/YoungY620/springcloud-config.git
      label: master
server:
  port: 7755