server:
  port: 6001
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka2.com:7002/eureka/,http://eureka1.com:7001/eureka/
  instance:
    instance-id: gateway.com
    # 访问路径可以显示IP地址
    prefer-ip-address: true
zuul:
  routes:
    user:
      serviceId: feign
      path: /e-shop/**
  ignored-services: feign # 为了安全，忽略原服务名
#      ignored-services: "*"
  prefix: /neu
