server:
  port: 80
spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defaultZone: http://eureka2.com:7002/eureka/, http://eureka1.com:7001/eureka/
#    register-with-eureka: false
